
# Only describes hidden layers
layers:
  - n_nodes: 3                   # Layer 1
    activation: 'tanh'
  - n_nodes: 3
    activation: 'tanh'
  - n_nodes: 3
    activation: 'tanh'
  - n_nodes: 2
    activation: 'tanh'
  - n_nodes: 2                    # Layer L - 1
    activation: 'tanh'

# Only describes output layers
output:
  n_nodes: 1
  activation: 'sigmoid'
